from app.singletons import db


class Candidate(db.Model):

    __tablename__ = 'candidate'

    dod_id = db.Column(db.String, primary_key=True)
    first_name = db.Column(db.String, nullable=False)
    last_name = db.Column(db.String, nullable=False)
    education_level_id = db.Column(db.String, db.ForeignKey('education_level.code'))
    education_level = db.relationship('EducationLevel')
    mos_level_id = db.Column(db.String, db.ForeignKey('mos_level.code'))
    mos_level = db.relationship('MOSLevel')
    rank_level_id = db.Column(db.String, db.ForeignKey('rank_level.code'))
    rank_level = db.relationship('RankLevel')
    id = db.Column(db.String, nullable=False)
    middle_initial = db.Column(db.String, nullable=False)
    social_security_number = db.Column(db.String, nullable=False)
    phone_number = db.Column(db.String, nullable=False)
    dob = db.Column(db.Date, nullable=False)
    sex = db.Column(db.String, nullable=False)
    active_service_date = db.Column(db.Date, nullable=False)
    arrival_date = db.Column(db.Date, nullable=False)
    dmsl = db.Column(db.String, nullable=False)
    gt_score = db.Column(db.String, nullable=False)
    contract_acquistion = db.Column(db.String, nullable=False)
    emergency_contact_first_name = db.Column(db.String, nullable=False)
    emergency_contact_last_name = db.Column(db.String, nullable=False)
    emergency_contact_phone_number = db.Column(db.String, nullable=False)
    emergency_contact_relationship = db.Column(db.String, nullable=False)
    time_standard = db.Column(db.String, nullable=False)
    attended = db.Column(db.Boolean, nullable=False)
    failure_code = db.Column(db.String, nullable=False)
    failure_comment = db.Column(db.String, nullable=False)
    datetime_creation = db.Column(db.TIMESTAMP, server_default=db.func.current_timestamp(), nullable=False)
    datetime_update = db.Column(db.TIMESTAMP, server_default=db.func.current_timestamp(), onupdate=db.func.current_timestamp(), nullable=False)
    home_of_record = db.Column(db.String, nullable=False)
    arrived_from = db.Column(db.String, nullable=False)
    has_dependents = db.Column(db.Boolean, nullable=False)
    ranger_regiment_discovered = db.Column(db.String, nullable=False)
    is_tdy = db.Column(db.Boolean, nullable=False)
    tdy_unit = db.Column(db.String, nullable=False)
    played_sports = db.Column(db.Boolean, nullable=False)
    sports_played = db.Column(db.String, nullable=False)
    has_hot_weather_injury = db.Column(db.Boolean, nullable=False)
    has_cold_weather_injury = db.Column(db.Boolean, nullable=False)
    has_physical = db.Column(db.Boolean, nullable=False)
    has_airborne = db.Column(db.Boolean, nullable=False)
    has_ranger_sof_affiliations = db.Column(db.Boolean, nullable=False)
    has_glasses = db.Column(db.Boolean, nullable=False)
    success_factors = db.Column(db.String, nullable=False)
    success_motivators = db.Column(db.String, nullable=False)
    bad_habits = db.Column(db.String, nullable=False)